apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-test
  template:
    metadata:
      labels:
        name: nginx-test
    spec:
      initContainers:
      - name: put-index
        image: "busybox:1.35.0"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "echo $HOSTNAME > /usr/share/nginx/html/index.html"]
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: index-html
      containers:
        - name: nginx-test
          image: "nginx:1.23.1"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index-html
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
      - name: index-html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    name: nginx-test
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: nginx-test
